[package]
name = "live-long-and-prospero"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", default-features = false, features = ["derive", "env", "error-context", "help", "std", "usage"] }
thiserror = "2.0.12"
